// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inafuqmhjsmxzlvtfvux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluYWZ1cW1oanNteHpsdnRmdnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MjQ3MDQsImV4cCI6MjA4ODEwMDcwNH0.gE1jE7TRNwE1S5-uYeuPTVzDgI_H1riUzN7as7fNIGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});